model:
  output_size: 2
  layers: [256, 128, 64, 32]
training:
  epochs: 3
  batch_size: 16
  learning_rate: 0.01
data:
  train_path: ../data/train_data.csv
  validation_path: ../data/validation_data.csv
device: cuda
