model:
  output_size: 2
  layers: [256, 128, 64, 32]
training:
  epochs: 50
  batch_size: 16
  learning_rate: 0.0001
data:
  train_path: data/modified_file.csv
  validation_path: data/coco_validation_data_with_occlusion.csv
device: cuda
